// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb_aJeJbcjzrzKGNCWvVzVHZk_v6oC2ug',
    appId: '1:250324165347:ios:b6fc9fac4fc6be3d839bd6',
    messagingSenderId: '250324165347',
    projectId: 'po-keat-fyp',
    storageBucket: 'po-keat-fyp.firebasestorage.app',
    iosBundleId: 'com.example.qrVirtualIdentity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb_aJeJbcjzrzKGNCWvVzVHZk_v6oC2ug',
    appId: '1:250324165347:ios:b6fc9fac4fc6be3d839bd6',
    messagingSenderId: '250324165347',
    projectId: 'po-keat-fyp',
    storageBucket: 'po-keat-fyp.firebasestorage.app',
    iosBundleId: 'com.example.qrVirtualIdentity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1kqvQfvs1B2GiAvmGlJbQ44kCfmx9Cd8',
    appId: '1:250324165347:web:ade1d12c84a44fde839bd6',
    messagingSenderId: '250324165347',
    projectId: 'po-keat-fyp',
    authDomain: 'po-keat-fyp.firebaseapp.com',
    storageBucket: 'po-keat-fyp.firebasestorage.app',
    measurementId: 'G-977JYRTZRF',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1kqvQfvs1B2GiAvmGlJbQ44kCfmx9Cd8',
    appId: '1:250324165347:web:ade1d12c84a44fde839bd6',
    messagingSenderId: '250324165347',
    projectId: 'po-keat-fyp',
    authDomain: 'po-keat-fyp.firebaseapp.com',
    storageBucket: 'po-keat-fyp.firebasestorage.app',
    measurementId: 'G-977JYRTZRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_T0hdVv-4iXXOKVxUmpld8RB8NMgf7H8',
    appId: '1:250324165347:android:23211a1a618661bb839bd6',
    messagingSenderId: '250324165347',
    projectId: 'po-keat-fyp',
    storageBucket: 'po-keat-fyp.firebasestorage.app',
  );
}
