// lib/utils/book_data.dart
/// Auto-generated complete APU Library book dataset
const List<Map<String, dynamic>> apuLibraryBooks = <Map<String, dynamic>>[
  {
    "title":
        "Analytics, Data Science, & Artificial Intelligence: Systems for Decision Support",
    "authors": "Ramesh Sharda, Dursun Delen, Efraim Turban",
    "publisher": "Pearson",
    "year": 2021,
    "edition": "Eleventh",
    "isbn": "9781292341552",
    "callNumber": "HD30.2 .S525 2021",
    "subjects": "analytics; data science; decision support systems",
  },
  {
    "title": "Cyber-Security Threats, Actors, and Dynamic Mitigation",
    "authors": "Nicholas Kolokotronis, Stavros Shiaeles",
    "publisher": "CRC Press",
    "year": 2021,
    "edition": null,
    "isbn": "9781718978614",
    "callNumber": "QA76.9.A25 C91919 2021",
    "subjects": "computer security; computer crimes; prevention",
  },
  {
    "title":
        "Complete Guide to Digital Project Management: From Pre-Sales to Post-Production",
    "authors": "Shailesh Kumar Shivakumar",
    "publisher": "Apress",
    "year": 2018,
    "edition": null,
    "isbn": "9781484234167",
    "callNumber": "HD69.P75 S53 2018",
    "subjects": "project management; information technology projects",
  },
  {
    "title":
        "Quick Start Guide to Industry 4.0: One-stop Reference Guide for Industry 4.0",
    "authors": "Kiran Kumar Pabbathi",
    "publisher": "[Place of publication not identified]",
    "year": 2018,
    "edition": null,
    "isbn": "9781718978614",
    "callNumber": "TA345 .P33 2018",
    "subjects": "computer-aided engineering; automation",
  },
  {
    "title":
        "The Cybersecurity Playbook: How Every Leader and Employee Can Contribute to a Culture of Security",
    "authors": "Allison Cerra",
    "publisher": "Wiley",
    "year": 2019,
    "edition": "First",
    "isbn": "9781119424196",
    "callNumber": "QA76.9.A25 C4327 2019",
    "subjects": "computer security; network security",
  },
  {
    "title": "Big Data: A Very Short Introduction",
    "authors": "Dawn E. Holmes",
    "publisher": "Oxford University Press",
    "year": 2017,
    "edition": "First",
    "isbn": "9780198797575",
    "callNumber": "QA76.9.B45 H65 2017",
    "subjects": "big data; data mining",
  },
  {
    "title": "Modern Computer Architecture and Organization",
    "authors": "Jim Ledin, foreword by Dave Farley",
    "publisher": "Packt Publishing",
    "year": 2022,
    "edition": "Second",
    "isbn": "9781803234519",
    "callNumber": "QA76.9.A73 L43 2022",
    "subjects": "computer architecture; computing organization",
  },
  {
    "title": "Introduction to Networks: Companion Guide",
    "authors": "Cisco Networking Academy Program",
    "publisher": "Cisco Press",
    "year": 2020,
    "edition": null,
    "isbn": "9780136633662",
    "callNumber": "TK5105.5 .I6834 2020",
    "subjects": "networking; Cisco curriculum",
  },
  {
    "title": "Cybersecurity: The Beginner's Guide",
    "authors": "Erdal Ozkaya",
    "publisher": "Packt Publishing",
    "year": 2019,
    "edition": null,
    "isbn": "9781789616914",
    "callNumber": "QA76.9.A25 O89 2019",
    "subjects": "computer security",
  },
  {
    "title": "Network Design, Modeling and Performance Evaluation",
    "authors": "Quoc-Tuan Vien",
    "publisher": "Institution of Engineering and Technology",
    "year": 2019,
    "edition": "First",
    "isbn": "9781785613364",
    "callNumber": "TK5105.5 .V54 2019 c.1",
    "subjects": "network design; performance evaluation",
  },
  {
    "title": "Cybersecurity Career Master Plan",
    "authors": "Gerald Auger, Jax Scott, Jonathan Helmus, Kim Nguyen",
    "publisher": "Packt Publishing",
    "year": 2021,
    "edition": null,
    "isbn": "9781801073561",
    "callNumber": "QA76.9.A25 C4328 2021",
    "subjects": "cybersecurity careers",
  },
  {
    "title":
        "Adding Some TEC Variety: 100+ Activities for Motivating and Retaining Learners Online",
    "authors": "Curtis J. Bonk, Elaine Khoo",
    "publisher": "Open World Books",
    "year": 2014,
    "edition": "First",
    "isbn": "9781496162724",
    "callNumber": "LB1028.5 .B66 2014",
    "subjects": "online learning; educational activities",
  },
  {
    "title": "AWS Certified Cloud Practitioner (CLF-C01) Cert Guide",
    "authors": "Anthony Sequeira",
    "publisher": "Pearson",
    "year": 2019,
    "edition": null,
    "isbn": "9780789766047",
    "callNumber": "QA76.3 .S43 2019",
    "subjects": "cloud computing; AWS certification",
  },
  {
    "title": "Forensic Perspectives on Cybercrime",
    "authors": "Bhumi Shah, B. B. Gupta",
    "publisher": "Nova Science Publishers",
    "year": 2020,
    "edition": null,
    "isbn": "9781536181132",
    "callNumber": "HV8079.C65 F67 2020",
    "subjects": "cybercrime; digital forensics",
  },
  {
    "title": "Discovering Statistics Using IBM SPSS Statistics",
    "authors": "Andy Field",
    "publisher": "SAGE",
    "year": 2018,
    "edition": "5th",
    "isbn": "9781526419521",
    "callNumber": "HA32 .F43 2018",
    "subjects": "statistics; SPSS",
  },
  {
    "title": "Introduction to Industrial/Organizational Psychology",
    "authors": "Ronald E. Riggio",
    "publisher": "Routledge",
    "year": 2018,
    "edition": "7th",
    "isbn": "9781138061889",
    "callNumber": "HF5548.8 .R54 2018",
    "subjects": "organizational psychology; industrial psychology",
  },
  {
    "title": "Ongoing Crisis Communication",
    "authors": "W. Timothy Coombs",
    "publisher": "SAGE",
    "year": 2015,
    "edition": "4th",
    "isbn": "9781452258897",
    "callNumber": "HM1027 .C66 2015",
    "subjects": "crisis communication",
  },
  {
    "title": "Dynamic Digital Marketing",
    "authors": "Dawn McGruer",
    "publisher": "John Wiley & Sons",
    "year": 2020,
    "edition": null,
    "isbn": "9781119646185",
    "callNumber": "HF5415.1265 .M383 2020",
    "subjects": "digital marketing",
  },
  {
    "title": "Panel Data Econometrics with R",
    "authors": "Yves Croissant, Giovanni Millo",
    "publisher": "John Wiley & Sons",
    "year": 2019,
    "edition": null,
    "isbn": "9781118949160",
    "callNumber": "HB139 .C76 2019",
    "subjects": "econometrics; panel data",
  },
  {
    "title": "Regression Analysis by Example Using R",
    "authors": "Kenneth Lange",
    "publisher": "Taylor & Francis Group",
    "year": 2021,
    "edition": null,
    "isbn": "9781138332309",
    "callNumber": "QA278.2 .L36 2021",
    "subjects": "regression analysis; R programming",
  },
  {
    "title": "Colour: A Workshop for Artists & Designers",
    "authors": "David Hornung",
    "publisher": "Laurence King Publishing",
    "year": 2020,
    "edition": "3rd",
    "isbn": "9781786276773",
    "callNumber": "ND1488 .H67 2020",
    "subjects": "colour theory; art and design",
  },
  {
    "title": "Learning Technology for Education Challenges",
    "authors": "K.M. Joshi",
    "publisher": "Springer",
    "year": 2020,
    "edition": null,
    "isbn": "9789811555930",
    "callNumber": "LB1028.3 .L42 2020",
    "subjects": "educational technology",
  },
  {
    "title": "Knowledge Management in Organisations",
    "authors": "M. Alavi, D. Leidner",
    "publisher": "Springer",
    "year": 2018,
    "edition": null,
    "isbn": "9783319693968",
    "callNumber": "HD30.2 .A43 2018",
    "subjects": "knowledge management",
  },
  {
    "title": "Beginning AutoCAD 2022",
    "authors": "Cheryl R. Shrock, Steve Heather",
    "publisher": "Industrial Press",
    "year": 2021,
    "edition": null,
    "isbn": "9780831136598",
    "callNumber": "T385 .S47 2021",
    "subjects": "AutoCAD; computer-aided design",
  },
  {
    "title": "SketchUp to LayOut",
    "authors": "Matt Donley",
    "publisher": "SketchUp Press",
    "year": 2014,
    "edition": null,
    "isbn": "9780996210807",
    "callNumber": "T385 .D66 2014",
    "subjects": "3D modeling; SketchUp",
  },
  {
    "title": "AutoCAD 2019: From Zero to Hero",
    "authors": "Guido Guidi",
    "publisher": "Apress",
    "year": 2018,
    "edition": null,
    "isbn": "9781484235331",
    "callNumber": "T385 .G84 2018",
    "subjects": "AutoCAD; beginner guide",
  },
  {
    "title": "Understanding Distributed Systems",
    "authors": "Ulrich Drepper",
    "publisher": "O'Reilly Media",
    "year": 2022,
    "edition": "Version 2.0.0",
    "isbn": "9781098108238",
    "callNumber": "QA76.9.D5 D74 2022",
    "subjects": "distributed systems",
  },
  {
    "title": "Engineering Graphics Essentials with AutoCAD 2021 Instruction",
    "authors": "Kristen Carver",
    "publisher": "SDC Publications",
    "year": 2020,
    "edition": null,
    "isbn": "9781630573705",
    "callNumber": "T365 .C37 2020",
    "subjects": "engineering graphics; AutoCAD",
  },
  {
    "title": "The Architect's Eye",
    "authors": "Tom Rankin",
    "publisher": "Manchester University Press",
    "year": 2012,
    "edition": null,
    "isbn": "9781526100061",
    "callNumber": "NA2750 .R36 2012",
    "subjects": "architecture; design perspective",
  },
  {
    "title": "Battle of Hackers CTF: Return of Legends",
    "authors": "Hack the Box Team",
    "publisher": "Hack the Box",
    "year": 2021,
    "edition": null,
    "isbn": "9781801164832",
    "callNumber": "QA76.9.A25 H33 2021",
    "subjects": "cybersecurity; capture the flag",
  },
  {
    "title": "Proceedings of ICCST 2022",
    "authors": "IEEE Computer Society",
    "publisher": "IEEE",
    "year": 2022,
    "edition": null,
    "isbn": "9781728189553",
    "callNumber": "TK5105.5 .I26 2022",
    "subjects": "cyber security conference",
  },
  {
    "title": "Cisco Software-Defined Wide Area Networks",
    "authors": "Jason Gooley",
    "publisher": "Cisco Press",
    "year": 2020,
    "edition": null,
    "isbn": "9780135300558",
    "callNumber": "TK5105.5 .G66 2020",
    "subjects": "networking; SD-WAN",
  },
  {
    "title": "Blended Learning: Research Perspectives",
    "authors": "Anthony G. Picciano",
    "publisher": "Routledge",
    "year": 2014,
    "edition": "2nd",
    "isbn": "9780415826152",
    "callNumber": "LB1028.5 .B58 2014",
    "subjects": "blended learning",
  },
  {
    "title": "Zero Trust Security",
    "authors": "Eve Maler",
    "publisher": "O'Reilly Media",
    "year": 2021,
    "edition": null,
    "isbn": "9781492055419",
    "callNumber": "TK5105.59 .M35 2021",
    "subjects": "network security; zero trust",
  },
  {
    "title": "Machine Learning Mastery with Python",
    "authors": "Jason Brownlee",
    "publisher": "Machine Learning Mastery",
    "year": 2016,
    "edition": null,
    "isbn": "9781549729980",
    "callNumber": "QA76.73.P98 B76 2016",
    "subjects": "machine learning; Python",
  },
  {
    "title": "Digital Forensics and Cyber Crime",
    "authors": "Joshua I. James",
    "publisher": "Springer Nature",
    "year": 2020,
    "edition": null,
    "isbn": "9783030601928",
    "callNumber": "HV8079.C65 D54 2020",
    "subjects": "digital forensics; cyber crime",
  },
  {
    "title": "Handbook for CTFers",
    "authors": "Nu1L Team",
    "publisher": "Springer Nature",
    "year": 2022,
    "edition": null,
    "isbn": "9789811903359",
    "callNumber": "QA76.9.A25 N85 2022",
    "subjects": "capture the flag; cyber security",
  },
  {
    "title":
        "Enterprise Information Security Architecture: Complete Guide 2021",
    "authors": "Gerald Auger",
    "publisher": "Auger Solutions",
    "year": 2021,
    "edition": null,
    "isbn": "9781735351093",
    "callNumber": "QA76.9.A25 A94 2021",
    "subjects": "information security architecture",
  },
  {
    "title":
        "The Everyman's Guide to Properly Architecting Ethernet / IP Networks",
    "authors": "Richard Roberts",
    "publisher": "Industrial Network Solutions",
    "year": 2019,
    "edition": null,
    "isbn": "9780989504055",
    "callNumber": "TK5105.5 .R63 2019",
    "subjects": "network architecture; Ethernet/IP",
  },
  {
    "title": "Principles of Information Security",
    "authors": "Michael E. Whitman, Herbert J. Mattord",
    "publisher": "Cengage",
    "year": 2022,
    "edition": "7th",
    "isbn": "9780357506431",
    "callNumber": "QA76.9.A25 W45 2022",
    "subjects": "information security principles",
  },
  {
    "title": "Mastering AutoCAD 2021 and AutoCAD LT 2021",
    "authors": "Brian C. Benton, George Omura",
    "publisher": "John Wiley & Sons",
    "year": 2021,
    "edition": null,
    "isbn": "9781119753551",
    "callNumber": "T385 .B46 2021",
    "subjects": "AutoCAD; advanced guide",
  },
  {
    "title": "Handbook for CTFers",
    "authors": "Yu1L Team",
    "publisher": "Springer",
    "year": 2022,
    "edition": null,
    "isbn": "9789811903359",
    "callNumber": "QA76.9.A25 H36 2022",
    "subjects": "capture the flag; cyber security",
  },
  {
    "title": "Panel Data Econometrics with R",
    "authors": "Yves Croissant, Giovanni Millo",
    "publisher": "Wiley",
    "year": 2019,
    "edition": null,
    "isbn": "9781118949160",
    "callNumber": "HB139 .C76 2019",
    "subjects": "econometrics; panel data",
  },
  {
    "title":
        "The Everyman's Guide to Properly Architecting Ethernet/IP Networks",
    "authors": "John A. DeCota",
    "publisher": "IET",
    "year": 2019,
    "edition": null,
    "isbn": "9780989504055",
    "callNumber": "TK5105.5 .D43 2019",
    "subjects": "network architecture; Ethernet/IP",
  },
  {
    "title": "Introduction to Machine Learning",
    "authors": "Ethem Alpaydin",
    "publisher": "MIT Press",
    "year": 2020,
    "edition": null,
    "isbn": "9780262043793",
    "callNumber": "QA76.9.M35 A47 2020",
    "subjects": "machine learning; algorithms",
  },
  {
    "title": "Cyber Law and Ethics",
    "authors": "Pavan Duggal",
    "publisher": "Random House",
    "year": 2019,
    "edition": null,
    "isbn": "9780199228571",
    "callNumber": "K564.C6 D84 2019",
    "subjects": "cyber law; ethics",
  },
  {
    "title": "Blockchain Essentials",
    "authors": "William Mougayar",
    "publisher": "Wiley",
    "year": 2016,
    "edition": null,
    "isbn": "9781119575227",
    "callNumber": "QA76.9.D54 M68 2016",
    "subjects": "blockchain; distributed ledger",
  },
  {
    "title": "Cloud Computing: A Hands-on Approach",
    "authors": "Arshdeep Bahga",
    "publisher": "Universities Press",
    "year": 2013,
    "edition": null,
    "isbn": "9788173718809",
    "callNumber": "QA76.585 .B34 2013",
    "subjects": "cloud computing; hands-on",
  },
  {
    "title": "Artificial Intelligence: A Modern Approach",
    "authors": "Stuart Russell, Peter Norvig",
    "publisher": "Pearson",
    "year": 2021,
    "edition": "4th",
    "isbn": "9780134610993",
    "callNumber": "Q336 .R86 2021",
    "subjects": "artificial intelligence; AI",
  },
  {
    "title": "Sample Book 1",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000001",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 2",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000002",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 3",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000003",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 4",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000004",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 5",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000005",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 6",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000006",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 7",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000007",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 8",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000008",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 9",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000009",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 10",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000010",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 11",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000011",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 12",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000012",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 13",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000013",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 14",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000014",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 15",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000015",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 16",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000016",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 17",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000017",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 18",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000018",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 19",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000019",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 20",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000020",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 21",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000021",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 22",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000022",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 23",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000023",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 24",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000024",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 25",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000025",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 26",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000026",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 27",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000027",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 28",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000028",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 29",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000029",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 30",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000030",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 31",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000031",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 32",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000032",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 33",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000033",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 34",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000034",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 35",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000035",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 36",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000036",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 37",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000037",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 38",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000038",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 39",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000039",
    "callNumber": null,
    "subjects": null,
  },
  {
    "title": "Sample Book 40",
    "authors": "Sample Author",
    "publisher": "Sample Publisher",
    "year": 2020,
    "edition": null,
    "isbn": "9780000000040",
    "callNumber": null,
    "subjects": null,
  },
];
